### ISSUE TITLE
The compressionLevel handling for LZ4 does not work

### ISSUE THREAD

**Issue by petrikero** [aloneguid/ironcompress#17]
It seems that the LZ4 compressor only actually compresses if given the `CompressionLevel.Fastest` flag:
```
Iron iron = new Iron(ArrayPool<byte>.Shared);
using (IronCompressResult lz4 = iron.Compress(Codec.LZ4, uncompressed.AsSpan()))
    Console.WriteLine("LZ4 (optimal): {0} bytes ({1:0.00}%)", lz4.Length, lz4.Length * 100.0 / uncompressed.Length);
using (IronCompressResult lz4 = iron.Compress(Codec.LZ4, uncompressed.AsSpan(), compressionLevel: CompressionLevel.SmallestSize))
    Console.WriteLine("LZ4 (smallest): {0} bytes ({1:0.00}%)", lz4.Length, lz4.Length * 100.0 / uncompressed.Length);
using (IronCompressResult lz4 = iron.Compress(Codec.LZ4, uncompressed.AsSpan(), compressionLevel: CompressionLevel.Fastest))
    Console.WriteLine("LZ4 (fastest): {0} bytes ({1:0.00}%)", lz4.Length, lz4.Length * 100.0 / uncompressed.Length);
```

This results in the following output:
```
LZ4 (optimal): 206368 bytes (100,39%) native
LZ4 (smallest): 206368 bytes (100,39%) native
LZ4 (fastest): 109516 bytes (53,28%) native
```
That is, only `CompressionLevel.Fastest` actually does any compression.

The issue seems to be that `ToNativeCompressionLevel()` converts `CompressionLevel.Optimal` to the value 2, but then `compress_lz4()` in `api.cpp` converts the value 2 to `level = 32768`. This is passed to LZ4 as the `acceleration_level` where a higher number means less compression.

So looks like the `compress_lz4()` interprets the converted-to-native compression level in an incorrect fashion.

For reference, the Zstandard seems to handle the levels as expected:
```
Zstd (optimal): 64226 bytes (31,24%)
Zstd (smallest): 63076 bytes (30,68%)
Zstd (fastest): 73317 bytes (35,67%)
```

**Comment by crodwell** [comment]
+1, also verified this behaviour.
