### ISSUE TITLE
Compression Level

### ISSUE THREAD

**Issue by Jure-BB** [aloneguid/ironcompress#6]
Hello,

Is there a way to set a compression level?

**Comment by Jure-BB** [comment]
Hehe :) Still, are there any plans to add it, or is it out of scope for this library?

Some compression algorithms have quite different tradeoffs at different compression levels. 

I really like the design of this library. Using native, original implementations, supporting multiple platforms, use of Span to avoid unnecessary copying and simple intuitive API.

**Comment by aloneguid** [comment]
Thanks) Yes it would be great to add it, probably has to be something like an enum per method, as levels don't always align. No promises on timing as always, and you're welcome to give it a go if you want.

**Comment by aloneguid** [comment]
Thanks, I always wanted to do this

**Comment by aloneguid** [comment]
It's available now ;)
